// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploaderApp.API.Data;

namespace UploaderApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201127173651_AddDocInfo")]
    partial class AddDocInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UploaderApp.API.Models.DocumentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentFullName")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("SalesforceId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("UniqueLinkId")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("dateAgreed")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateResent")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateSent")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateViewed")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("DocumentInfo");
                });

            modelBuilder.Entity("UploaderApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
